//! The words of a language: lemmas by how often they are met, the forms each
//! one takes, and how it sounds.
//!
//! A lexicon is reference data about a language, not material for a learner,
//! which is why it is built into the binary rather than loaded like a pack:
//! the version of hilvan is the version of its lexicon, and there is no
//! second copy in the database to drift from it. `lexicons/en/lexicon.tsv` is
//! generated by `tools/lexicon/build.py` from wordfreq, the English Speller
//! Database, UD English-EWT and `CMUdict` - see `lexicons/en/README.md` for the
//! sources and their licence.

use std::collections::HashMap;
use std::sync::LazyLock;

use serde::Serialize;

/// The levels a learner aims at: the commonest thousand lemmas, two
/// thousand, five thousand. Cumulative - knowing the 2k level means knowing
/// the first two thousand, not the second - because that is how a learner
/// says it ("I know two thousand words"). A product decision, the same for
/// every language.
pub const LEVELS: [u32; 3] = [1000, 2000, 5000];

/// One lemma of the lexicon.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    /// 1 for the commonest lemma of the language.
    pub rank: u32,
    /// As it is written: "go", "I", "Monday".
    pub lemma: String,
    /// The transcription, IPA; `None` when the source has none.
    pub ipa: Option<String>,
    /// Every other spelling it takes, lowercase: "went", "gone", "goes".
    pub forms: Vec<String>,
}

impl Entry {
    /// The smallest level that holds this lemma, or `None` past the last.
    #[must_use]
    pub fn level(&self) -> Option<u32> {
        level(self.rank)
    }
}

/// The smallest level a rank falls in.
#[must_use]
pub fn level(rank: u32) -> Option<u32> {
    LEVELS.into_iter().find(|level| rank <= *level)
}

/// A language's lemmas, with the lookups the tutor needs.
#[derive(Debug)]
pub struct Lexicon {
    entries: Vec<Entry>,
    /// Lowercase lemma -> its entry.
    by_lemma: HashMap<String, usize>,
    /// Lowercase spelling -> every entry it is a spelling of: "left" is
    /// "leave" and "left".
    by_form: HashMap<String, Vec<usize>>,
}

/// A line of a lexicon file that cannot be read.
#[derive(Debug, thiserror::Error)]
#[error("line {line} of the lexicon is not `rank<TAB>lemma<TAB>ipa<TAB>forms`: {text:?}")]
pub struct Malformed {
    line: usize,
    text: String,
}

impl Lexicon {
    /// Reads a lexicon file: `#` comments, then one lemma a line.
    ///
    /// # Errors
    ///
    /// Fails on a line without four tab-separated fields or with a rank that
    /// is not a number - a lexicon with a hole in it would rank words wrong
    /// without saying so.
    pub fn parse(text: &str) -> Result<Self, Malformed> {
        let mut entries = Vec::new();
        for (index, line) in text.lines().enumerate() {
            let line = line.trim_end_matches('\r');
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let malformed = || Malformed {
                line: index + 1,
                text: line.to_string(),
            };
            let mut fields = line.split('\t');
            let (Some(rank), Some(lemma), Some(ipa), Some(forms), None) = (fields.next(), fields.next(), fields.next(), fields.next(), fields.next()) else {
                return Err(malformed());
            };
            let rank = rank.parse().map_err(|_| malformed())?;
            if lemma.is_empty() {
                return Err(malformed());
            }
            entries.push(Entry {
                rank,
                lemma: lemma.to_string(),
                ipa: (!ipa.is_empty()).then(|| ipa.to_string()),
                forms: forms.split(' ').filter(|form| !form.is_empty()).map(str::to_string).collect(),
            });
        }

        let mut by_lemma = HashMap::with_capacity(entries.len());
        let mut by_form: HashMap<String, Vec<usize>> = HashMap::with_capacity(entries.len() * 2);
        for (index, entry) in entries.iter().enumerate() {
            let key = entry.lemma.to_lowercase();
            by_form.entry(key.clone()).or_default().push(index);
            by_lemma.entry(key).or_insert(index);
            for form in &entry.forms {
                by_form.entry(form.clone()).or_default().push(index);
            }
        }
        Ok(Self { entries, by_lemma, by_form })
    }

    /// The lemma, whatever case it is asked in.
    #[must_use]
    pub fn entry(&self, lemma: &str) -> Option<&Entry> {
        self.by_lemma.get(&lemma.to_lowercase()).map(|&index| &self.entries[index])
    }

    /// Whether `spelling` is the lemma itself or one of its forms.
    #[must_use]
    pub fn is_spelling_of(&self, spelling: &str, lemma: &str) -> bool {
        let lemma = lemma.to_lowercase();
        self.by_form
            .get(&spelling.to_lowercase())
            .is_some_and(|entries| entries.iter().any(|&index| self.entries[index].lemma.to_lowercase() == lemma))
    }

    /// How many lemmas it holds.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether it holds none.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Every lemma, commonest first.
    pub fn entries(&self) -> impl Iterator<Item = &Entry> {
        self.entries.iter()
    }
}

static ENGLISH: LazyLock<Lexicon> = LazyLock::new(|| {
    // Built into the binary and parsed by a test on every gate run, so a
    // malformed file never reaches a stand: this cannot fail at runtime
    // without failing the build first.
    Lexicon::parse(include_str!("../lexicons/en/lexicon.tsv")).unwrap_or_else(|error| panic!("the English lexicon is malformed: {error}"))
});

/// The lexicon of a language, when hilvan has one.
#[must_use]
pub fn of(language: &str) -> Option<&'static Lexicon> {
    match language {
        "en" => Some(&ENGLISH),
        _ => None,
    }
}

/// A word of a sentence, as it stands in it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Token<'a> {
    /// As written: "Went", "doctor's".
    pub text: &'a str,
    /// Where it starts, counted in characters - what the app highlights by.
    pub start: usize,
}

impl Token<'_> {
    /// The spelling a lexicon is asked about: lowercase, a curly apostrophe
    /// made straight, and a possessive taken off - "doctor's" is "doctor".
    #[must_use]
    pub fn spelling(&self) -> String {
        let lower = self.text.to_lowercase().replace('\u{2019}', "'");
        lower.strip_suffix("'s").map_or_else(|| lower.clone(), str::to_string)
    }
}

/// The words of a sentence: letters, joined by an apostrophe or a hyphen
/// inside a word ("don't", "well-known"), everything else a separator.
#[must_use]
pub fn tokens(text: &str) -> Vec<Token<'_>> {
    let mut tokens = Vec::new();
    let mut start: Option<(usize, usize)> = None;
    let chars: Vec<(usize, char)> = text.char_indices().collect();
    for (position, &(byte, ch)) in chars.iter().enumerate() {
        let joins = matches!(ch, '\'' | '\u{2019}' | '-') && start.is_some() && chars.get(position + 1).is_some_and(|(_, next)| next.is_alphabetic());
        if ch.is_alphabetic() || joins {
            start.get_or_insert((byte, position));
        } else if let Some((from, at)) = start.take() {
            tokens.push(Token {
                text: &text[from..byte],
                start: at,
            });
        }
    }
    if let Some((from, at)) = start {
        tokens.push(Token {
            text: &text[from..],
            start: at,
        });
    }
    tokens
}

/// Where a lemma stands in a sentence: the first word that is the lemma or
/// one of its forms.
///
/// Without a lexicon for the language, only the lemma's own spelling is
/// found: a guess at another language's morphology would be a wrong answer
/// given with confidence.
#[must_use]
pub fn find<'a>(lexicon: Option<&Lexicon>, sentence: &'a str, lemma: &str) -> Option<Token<'a>> {
    let wanted = lemma.to_lowercase();
    tokens(sentence).into_iter().find(|token| {
        let spelling = token.spelling();
        spelling == wanted || lexicon.is_some_and(|lexicon| lexicon.is_spelling_of(&spelling, lemma))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const SMALL: &str = "# a comment\n1\tgo\tɡoʊ\tgoes going gone went\n2\tleave\tliv\tleaves leaving left\n3\tleft\tlɛft\t\n4\tI\taɪ\t\n";

    #[test]
    fn the_shipped_lexicon_reads_whole() {
        // The gate on the file the binary carries: a malformed line here
        // would be a panic on the stand.
        let english = of("en").expect("hilvan ships an English lexicon");
        assert!(
            english.len() >= 10_000,
            "the lexicon should reach well past the 5k level, holds {}",
            english.len()
        );
        let ranks: Vec<u32> = english.entries().map(|entry| entry.rank).collect();
        assert!(ranks.windows(2).all(|pair| pair[1] == pair[0] + 1), "ranks should run 1, 2, 3 without a gap");
        assert_eq!(ranks.first(), Some(&1));
    }

    #[test]
    fn the_shipped_lexicon_knows_the_common_words_and_their_forms() {
        let english = of("en").unwrap();
        let go = english.entry("go").expect("go");
        assert!(go.rank < 100, "go is among the commonest verbs, ranked {}", go.rank);
        assert!(english.is_spelling_of("went", "go"));
        assert!(english.is_spelling_of("children", "child"));
        assert!(english.is_spelling_of("is", "be"));
        assert_eq!(
            english.entry("i").map(|entry| entry.lemma.as_str()),
            Some("I"),
            "the pronoun is written in capitals"
        );
        assert!(english.entry("Monday").is_some(), "a day is a word, capital or not");
        // "john" is a word too, a rare one: what must not happen is the name
        // carrying it into the levels a learner aims at.
        for name in ["john", "china"] {
            assert!(
                english.entry(name).is_none_or(|entry| entry.level().is_none()),
                "{name} climbed into the levels on the strength of a name"
            );
        }
        assert!(
            english
                .entry("doctor")
                .and_then(|entry| entry.ipa.as_deref())
                .is_some_and(|ipa| ipa.contains('ˈ'))
        );
    }

    #[test]
    fn a_rank_falls_in_the_smallest_level_that_holds_it() {
        assert_eq!(level(1), Some(1000));
        assert_eq!(level(1000), Some(1000));
        assert_eq!(level(1001), Some(2000));
        assert_eq!(level(4999), Some(5000));
        assert_eq!(level(5001), None);
    }

    #[test]
    fn a_spelling_can_belong_to_two_lemmas() {
        let lexicon = Lexicon::parse(SMALL).unwrap();
        assert!(lexicon.is_spelling_of("left", "leave"));
        assert!(lexicon.is_spelling_of("left", "left"));
        assert!(lexicon.is_spelling_of("Went", "GO"), "case is not a different word");
        assert!(!lexicon.is_spelling_of("went", "leave"));
    }

    #[test]
    fn a_malformed_line_is_refused_with_its_number() {
        let error = Lexicon::parse("1\tgo\tɡoʊ\tgoes\nnot-a-rank\tbe\tbi\t\n").unwrap_err();
        assert!(error.to_string().contains("line 2"), "{error}");
        assert!(Lexicon::parse("1\tgo\n").is_err(), "a line with fields missing");
    }

    #[test]
    fn a_sentence_breaks_into_words_at_their_characters() {
        let found: Vec<(&str, usize)> = tokens("He isn't at the doctor's - well-known, ¿no?")
            .iter()
            .map(|token| (token.text, token.start))
            .collect();
        assert_eq!(
            found,
            vec![
                ("He", 0),
                ("isn't", 3),
                ("at", 9),
                ("the", 12),
                ("doctor's", 16),
                ("well-known", 27),
                ("no", 40)
            ]
        );
        // Counted in characters, not bytes: the app indexes by code point.
        let russian = tokens("Он дома.");
        assert_eq!(russian[1].start, 3);
        assert_eq!(russian[1].text, "дома");
    }

    #[test]
    fn a_lemma_is_found_by_any_of_its_forms() {
        let lexicon = Lexicon::parse(SMALL).unwrap();
        let token = find(Some(&lexicon), "She went home.", "go").expect("went is a form of go");
        assert_eq!((token.text, token.start), ("went", 4));
        assert!(find(Some(&lexicon), "She stayed home.", "go").is_none());
        assert_eq!(find(Some(&lexicon), "The doctor's bag.", "doctor").map(|token| token.text), Some("doctor's"));
    }

    #[test]
    fn without_a_lexicon_only_the_lemma_itself_is_found() {
        assert!(find(None, "Ella fue a casa.", "ir").is_none(), "no guessing at Spanish verbs");
        assert_eq!(find(None, "Voy a casa.", "casa").map(|token| token.start), Some(6));
    }
}
